### ISSUE TITLE
PHP-FPM Causes Login Issue 

### ISSUE THREAD

**Issue by premierplates** [blackfyre/ldvsc#2]
I have an admin area within our site with username and password login requirements.

I am running php 5.6 on an apache server and without php-fpm active, all works well with a login file controlling access to the admin area of the site.

When activating php-fpm on the server the admin login will not function, and will give no error message whilst no record of an error is captured within the error logs for the site. 

The php-fpm module auto detects the version of php in use and is configured to report errors to the error log but does not report the failed login attempts. There are no error messages on screen when attempting to login multiple times.

Any thoughts or experience of login issues associated with the use of php-fpm on an apache 2.4 server with php5.6 would be appreciated.

**Comment by blackfyre** [comment]
This environment wasn't created with PHP 5.6 and Apache in mind, and I don't even remember putting Apache into the mix...
I do believe that you're better off asking this question on StackOverflow.
